### ISSUE TITLE
General question about the implementation

### ISSUE THREAD

**Issue by superarts** [antonguzun/lazy_crafter#2]
Sorry about this noob question. I haven't dug into the source code yet, only looking at the `data` so far. I assume you are copying from the items in game after each craft attempt instead of reading from memory, which will give you something like this:

```
Item Class: Utility Flasks
Rarity: Magic
Investigator's Jade Flask of the Hare
--------
Quality: +20% (augmented)
Lasts 8.40 (augmented) Seconds
Consumes 30 of 60 Charges on use
Currently has 60 Charges
+1500 to Evasion Rating
--------
Requirements:
Level: 27
--------
Item Level: 85
--------
Used when Charges reach full (enchant)
--------
20% increased Duration
6% increased Movement Speed during Effect
--------
Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.

```

At this point, you won't have any access to the actual mods. It would be possible to match it with some regex "[0-9]\% increased Movement Speed during Effect", but what's the use of `mods.mini.json`? It looks to me that in the `stats`:

```json
{
	"English": [{
		"condition": [{}],
		"format": ["+#"],
		"index_handlers": [
			[]
		],
		"string": "{0}% to Chaos Resistance"
	}],
	"ids": ["base_chaos_damage_resistance_%"]
}
```

Only the `English` object makes sense. The IDs can be checked with `mods`, but to me it's overcomplicated. This app doesn't need to check item type. As long as it lists all mods, or even let user to enter a regex, it should be enough. Which looks like:

1. User selects one or more regex from a list, or enter it by himself (e.g. "increased Movement Speed during Effect")
2. User starts right click on a currency, hover mouse to the item he wants to craft, then hit some hotkey to start this app
3. This app `shift+click` -> `ctrl+c` -> `regexList.forEach { if copiedText.matches(regex) stopAndDingDong() }`

In this way, you don't need to maintain a list of item types. You don't need to maintain the mods list when a new version comes out. You can keep supporting it, but even if you don't, users can add their own regex to craft things they are interested in, e.g. all future cluster notables, and the mods this app doesn't support right now.

Having these being said, I often find that if I think there's something wrong with the system design, it's not because the system is flawed. It usually means I'm missing some big picture here. If anyone could tell me what's missing in my discussion above, it would be much appreicated.

**Comment by antonguzun** [comment]
Hi, Leo!

I appreciate your interest.

There are several reasons why I am trying to work with structured objects.

1. The app's goal is not clicker and matching only. I'm planning to add craft probability and expected cost estimation.  That's why I need mods with their stats, weights, and types.

2. I'm afraid I can't handle all edge cases with regexps. Probably, It's not possible to test all mod representations automatically with regexp. We have around 10k of mods. 
If you are sure that this is possible to cover all of them, please tell me. Because I am afraid to spend too much time discovering the wrong way.  

3. There is no chance to save the user from his mod-picking mistake with the regexp design. Non-perfect regexps are possible too.
We don't let the user pick the wrong mod with the current design.
We don't render huge and messy amounts of regexps.
There is possible to show him mods only associated with his item base. So the user is not forced to use the app with poedb website.
I prefer to stop rolling if a program's mistake is revealed. Error handling is very easy with the current design. That helps to avoid criticism because of losing currency.

However, I'm sure the regexp searching would be a useful feature alongside the current design. You are right, it would help to keep the relevance of the app in case of a patch, data source outdating, or if the project is abandoned.

So I'll add it to my plans.

**Comment by superarts** [comment]
Thank you for the explanation about your design intention, that makes perfect sense! A craftofexile style tool would be really nice, although I can imagine a lot of dev work :D
